learning_journal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_journals.urls', namespace='learning_journals')),
]

learning_journals/urls.py
"""Defines the URLs for our Learning Journals (learning_journals)"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Home Page
    url(r'^$', views.index, name='index'),

    # Show all topics
    url(r'^topics/$', views.topics, name='topics'),

    # Topic details page
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing entries
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry, name='edit_entry'),
]

users/urls.py
"""URL pattern for users of the journal"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # The login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # The logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # User registration page
    url(r'^register/$', views.register, name='register'),
]

learning_journals/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A learning entry that a learner wants to track"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text

class Entry(models.Model):
    """What was learned about each topic that is added"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return the string of the model being represented"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_journals/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_journals/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import  reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """The home page"""
    return render(request, 'learning_journals/index.html')

@login_required
def topics(request):
    """Show all the topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_journals/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all associated entries for that topic"""
    topic = Topic.objects.get(id=topic_id)
    # Limit topics to only current owner
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_journals/topic.html', context)

@login_required
def new_topic(request):
    """Add a topic"""
    if request.method != 'POST':
        # No data submitted, so create a blank form
        form = TopicForm()
    else:
        # Data submitted
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_journals:topics'))
    context = {'form': form}
    return render(request, 'learning_journals/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for the topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted
        form = EntryForm()
    else:
        # Data submitted
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_journals:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_journals/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit and existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Pre-fill form with the current entry data
        form = EntryForm(instance=entry)
    else:
        # data submitted, process it
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_journals:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_journals/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def logout_view(request):
    """User Log out"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_journals:index'))

def register(request):
    """New User Registration"""
    if request.method != 'POST':
        # Display empty registration form
        form = UserCreationForm()
    else:
        # Process the completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log user in and proceed to the index page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_journals:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_journals/templates/learning_journals/base.html
<!-- This is a template for the other pages to pull from, pretty basic right now 4/12/16 -->
<!-- Updated with some additional styling 4/16/16 -->

{% load bootstrap3 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

</body>
</html>>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Journal</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>

    <!-- Navigation bar stuff -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle-collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_journals:index' %}">Learning Journal</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_journals:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div> <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- end of container -->
</body>
</html>

learning_journals/templates/learning_journals/edit_entry.html
{% extends "learning_journals/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Edit entry</h2>
{% endblock header %}

{% block content %}

    <p><a href="{% url 'learning_journals:topic' topic.id %}">{{ topic }}</a></p>


    <form action="{% url 'learning_journals:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_journals/templates/learning_journals/index.html
{% extends "learning_journals/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Record Your Learning Progress</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make journal entries about your own learning progress.
    </h2>
    <h2>
        When you learn something new, create a topic and make an entry.  You can continue to create entries for each topic as you learn more.  This is a great way to summarize what you have learned.
    </h2>
{% endblock content %}

learning_journals/templates/learning_journals/new_entry.html
{% extends "learning_journals/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add new entry</h2>
{% endblock header %}

{% block content %}

    <p><a href="{% url 'learning_journals:topic' topic.id %}">{{ topic }}</a></p>

    <form action="{% url 'learning_journals:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_journals/templates/learning_journals/new_topic.html
{% extends "learning_journals/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic</h2>
{% endblock header %}

{% block content %}

    <form action ="{% url 'learning_journals:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_journals/templates/learning_journals/topic.html
{% extends 'learning_journals/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

<p>
    <a href="{% url 'learning_journals:new_entry' topic.id %}">Add new entry</a>
</p>

{% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'learning_journals:edit_entry' entry.id %}">Edit entry</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>

{% empty %}
    There are no entries for this topic yet.
{% endfor %}

{% endblock content %}

learning_journals/templates/learning_journals/topics.html
{% extends "learning_journals/base.html" %}

{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_journals:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'learning_journals:new_topic' %}">Add a new topic</a></h3>

{% endblock %}

users/templates/users/login.html
{% extends "learning_journals/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Login to your account</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_journals:index' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_journals/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Register an account</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_journals:index' %}"/>
    </form>
{% endblock content %}